export const fieldLabels: Record<string, string> = {
  departure_city: "Ville de départ",
  arrival_city: "Ville d’arrivée",
  start_date: "Date de départ",
  end_date: "Date de retour",
  travelers_total: "Voyageurs",
  adults: "Adultes",
  children: "Enfants",
  room_type: "Type de chambre",
  passport_type: "Type de passeport / nationalité",
  passport_received: "Passeport reçu",
  residence_permit_received: "Titre de séjour reçu",
  ticket_received: "Billet reçu",
  missing_documents: "Documents manquants",
  total_amount: "Montant total",
  deposit_amount: "Acompte",
  balance_amount: "Solde",
  currency: "Devise",
  invoice_status: "État de la facture",
  payment_status: "État du paiement",
  summary: "Résumé",
};
